spring:
  data:
    mongodb:
      username: admin
      password: password
      host: localhost
      port: 27017
      database: oxygen-cylinder

logging:
  level:
    org:
      springframework:
        data:
          mongodb: DEBUG